#!/bin/bash

. lib/plugin_bash.sh

player="$2"
message="$3"

# triggers when a message is said in global chat
# variables available are as follows:
# <"$player"> "$message"

if [ "$message" = "xyzzy" ] ; then
	mc 'tp '"$player"' 0 4 0'
elif echo "$message" | grep -q -e 'https\?://.* ' -e 'https\?://.*$' ; then
	# todo: this doesn't like text before url, also rewrite
	url="$(echo "$message" | sed 's|^.*https?://|https?://|;s| .*$||')"
	mc tellraw @a [\"[-] [\",\{\"text\":\"link\",\"underlined\":true,\"clickEvent\":\{\"action\":\"open_url\",\"value\":\""$url"\"\}\},\"]\"]
elif [ "$message" = "test" ] ; then
	for i in $(seq 1 16) ; do
		mc 'execute '"$player"' ~ ~ ~ summon Pig'
		mc 'give '"$player"' dirt'
	done
else
	plugin_exit_code=1
fi
exit "$plugin_exit_code"
