#!/bin/bash

# triggers when entitydata <entity> {} is run, which spits out the entity's full NBT data
# variables are as follows
# The data tag did not change: "$nbtdata"

if echo "$nbtdata" | grep -q "^.*CustomName:\"tp\"" ; then
	mc say boop
fi
