#!/bin/bash

# triggers when an entity is teleported to another entity
# variables are as follows
# ["$executer": Teleported "$player" to "$destination"]

if [ "$player" = "tp" -a "$destination" = "Megabobster" ]; then
	mc entitydata @e[name=tp,tag=-,type=armor_stand] {}
fi
