#!/bin/bash

# triggers on running the save-all command
# no special variables

if [ "$executer" = "$ARMORSTAND" ] ; then # todo: figure out where exactly executer comes from
	zip -r "$BACKUP_DIR"/"$LEVEL_NAME"\_"$(date +%Y-%m-%d.%H.%M.%S)".zip "$MINECRAFT_DIR"/"$LEVEL_NAME"
	cd "$BACKUP_DIR" # todo: create directory or error if it doesn't exist
	ls -td "$LEVEL_NAME"* | sed -e '1,7d' | xargs -d '\n' rm
	cd "$WRAPPER_DIR"
	mc save-on
	mc_ignore_armorstand say Server backup complete.
fi
