#!/bin/bash

. lib/plugin_bash.sh

executer="$2"
message="$3"

# triggers when the /say command is run
# variables available are as follows:
# ["$executer"] "$message"

# todo: finish backup script
#if [ "$executer" = "Server" -a "$message" = "Server backing up." ] ; then
#	mc_ignore_armorstand say This will disable all wrapper-enhanced functionality until the backup is complete.
#	mc save-off
#	mc save-all flush
if [ "$message" = "test" ] ; then
	mc execute @r '~ ~ ~' summon Pig
else
	plugin_exit_code=1
fi
exit "$plugin_exit_code"
