#!/bin/bash

. lib/plugin_bash.sh

executer="$1"
message="$2"

# triggers when the /say command is run
# variables available are as follows:
# ["$executer"] "$message"

#if [ "$executer" = "Server" -a "$message" = "Server backing up." ] ; then # todo: finish backup script
if [ "$message" = "Server backing up." ] ; then
	mc_ignore_armorstand say This will disable all wrapper-enhanced functionality until the backup is complete.
	mc save-off
	mc save-all flush
elif [ "$message" = "test" ] ; then
	mc execute "@r[c=1]" '~ ~ ~' summon Pig
fi
