#!/bin/bash

. lib/plugin_bash.sh

executer="$1"
player="$2"
destination="$3"

# triggers when an entity is teleported to another entity
# variables are as follows
# ["$executer": Teleported "$player" to "$destination"]

if [ "$player" = "xyz" -a "$destination" = "Megabobster" ]; then
	mc entitydata @e[name=xyz,tag=-,type=armor_stand] {}
else
	plugin_exit_code=1
fi
exit "$plugin_exit_code"
