#!/bin/bash

. lib/plugin_bash.sh

executer="$2"
player="$3"
x="$4"
y="$5"
z="$6"

# triggers when an entity is teleported
# variables are as follows:
# ["$executer": Teleported "$player" to "$x", "$y", "$z"]

if [ "$player" = "Pig" ] ; then
	mc say "Teleported $player to $x, $y, $z."
else
	plugin_exit_code=1
fi
exit "$plugin_exit_code"
