#!/bin/bash

. lib/plugin_bash.sh

player="$1"
command=("${@:2}")

# triggers when a message starting with $PREFIX is said in global chat
# passes $command as an array so prefix commands can have arbitrary arguments
# variables available are as follows:
# <"$player"> $PREFIX"$command"

if [ "$player" = "Megabobster" -a "${command[0]}" = "halt" ] ; then
	wrapper "Wrapper halting..." # todo: config option
elif [ "${command[0]}" = "blend" ] ; then
	grabber="$player" # todo: make sure I can remove this line
	grab blend clear @a[name="$player",score_blend=0] minecraft:book -1 0
elif [ "${command[0]}" = "bork" ] ; then # test cases for grab error handling
	if [ "${command[1]}" = "1" ] ; then
		grab bork tellraw @a '["bork"]'		# ERR_GRAB_INPUT_NOT_RECEIVED
	elif [ "${command[1]}" = "2" ] ; then
		grab bork help				# ERR_MULTIPLE_GRAB_INPUTS
	elif [ "${command[1]}" = "3" ] ; then
		grab blend say bork			# ERR_UNEXPECTED_GRAB_INPUT
	elif [ "${command[1]}" = "4" ] ; then
		grab bork say bork			# ERR_INVALID_GRAB
	else
		mc tellraw "$player" '[{"text":"['"$ARMORSTAND"'] Usage: !bork <1-4>"}]'
	fi
elif [ "${command[0]}" = "run" ] ; then
	if [ "${command[1]}" -le "16" ] ; then
		if [ "${command[2]}" ] ; then
			for i in $(seq 1 "${command[1]}") ; do
				mc execute "$player" '~ ~ ~' "${command[@]:2}"
			done
		else
			mc tellraw "$player" '[{"text":"['"$ARMORSTAND"'] Usage: !run <1-16> <command>"}]'
		fi
	else
		mc tellraw "$player" '[{"text":"['"$ARMORSTAND"'] Usage: !run <1-16> <command>"}]'
	fi
elif [ "${command[0]}" = "level-name" ] ; then
	mc say "$LEVEL_NAME"
#elif [ "${command[0]}" = "xyz" ] ; then # todo: trigger like grab, not grab...
#	mc execute "$player" '~ ~ ~' summon ArmorStand '~ ~ ~' '{CustomName:"xyz",Invulnerable:true,Marker:true,Invisible:true,NoGravity:true,Tags:[0:"xyz"]}'
#	grab xyz tp @e[name=xyz,tag=xyz,c=1] '~ ~ ~'
else
	mc say "$ERR_INVALID_MESSAGE_COMMAND" "${command[0]}".
fi
