#!/bin/bash

. lib/plugin_bash.sh

grab="$1"
grabber="$2"
last_line="$3"

# triggers when the grab function is run
# variables available are "$grab", the argument passed to the grab function
# and "$grabber", the player relevant to the called grab function

if [ "$grab" = "smash" ] ; then
	if echo "$last_line" | grep -q '^The data tag did not change: .*$' ; then
		mc blockdata -11 4 -9
		mc scoreboard players set "$grabber" smash 0
	else
		mc say "$ERR_UNEXPECTED_GRAB_INPUT" "$grab"
	fi
else # make sure to leave this here
	plugin_exit_code=1
fi
exit "$plugin_exit_code"
