#!/bin/bash

. lib/plugin_bash.sh

command="$1"
executer="$2"

# triggers on failed execute commands
# variables available are as follows:
# Failed to execute '"$command"' as "$executer"

if [ "$command" = "scoreboard players set @e[type=Item,c=1,r=3] blend 2" ] ; then
	mc tellraw "$executer" [\"["$ARMORSTAND"] Put your item on the ground!\"]
	mc scoreboard players set "$executer" blend 0
fi
